// examples/solid/src/index.tsx
import "@fontsource/inter/latin-700.css";
import { hooks } from "./css";

import { render } from "solid-js/web";
import App from "./App";

render(
  () => (
    <>
      {/* eslint-disable-next-line solid/no-innerhtml */}
      <style innerHTML={hooks} />
      <App />
    </>
  ),
  document.getElementById("root")!,
);

// examples/preact/src/main.tsx
import "@fontsource/inter/latin-700.css";

import { render } from "preact";
import App from "./App";
import { css } from "./css-hooks";

render(
  <>
    {/* eslint-disable-next-line react/no-danger */}
    <style dangerouslySetInnerHTML={{ __html: css }} />
    <App />
  </>,
  document.getElementById("root")!,
);
