// examples/qwik/src/main.tsx
import "@fontsource/inter/latin-700.css";
import "@builder.io/qwik/qwikloader.js";

import { hooks } from "./css";

import { render } from "@builder.io/qwik";
import App from "./App";

render(
  document.getElementById("root")!,
  <>
    <style dangerouslySetInnerHTML={hooks} />
    <App />
  </>,
);

// examples/react/src/main.tsx
import "@fontsource/inter/latin-700.css";
import { hooks } from "./css-hooks";

import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <style dangerouslySetInnerHTML={{ __html: hooks }} />
    <App />
  </React.StrictMode>,
);
