// examples/qwik/src/main.tsx
import "@fontsource/inter/latin-700.css";
import "@builder.io/qwik/qwikloader.js";

import { render } from "@builder.io/qwik";

import App from "./App.js";
import { styleSheet } from "./css.js";

render(
  document.getElementById("root")!,
  <>
    <style dangerouslySetInnerHTML={styleSheet()} />
    <App />
  </>,
);

// example/src/main.tsx
import "@fontsource/inter/latin-700.css";

import React from "react";
import ReactDOM from "react-dom/client";

import { App } from "./app.tsx";
import { styleSheet } from "./css.ts";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <style dangerouslySetInnerHTML={{ __html: styleSheet() }} />
    <App />
  </React.StrictMode>,
);
